PermissionsBasedProject/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PermissionsBasedProject.Constants;

namespace PermissionsBasedProject.Controllers
{
    public class ProductsController : Controller
    {
        [Authorize(Permissions.Products.View)]
        public IActionResult Index()
        {
            return View();
        }
    }
}

PermissionsBasedProject/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PermissionsBasedProject.Constants;
using PermissionsBasedProject.Models;

namespace PermissionsBasedProject.Controllers
{
    [Authorize(Permissions.Roles.View)]
    public class RolesController : Controller
    {
        private RoleManager<IdentityRole> _roleManager;

        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        // GET: RolesController
        [Authorize(Permissions.Roles.View)]
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        // GET: RolesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: RolesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RolesController/Create
        [Authorize(Permissions.Roles.Create)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RoleFormViewModel model)
        {
            try
            {

                if (!ModelState.IsValid)
                {
                    return View("Index" , await _roleManager.Roles.ToListAsync()); 
                }

                if(await _roleManager.RoleExistsAsync(model.Name))
                {
                    ModelState.AddModelError("Name","Role already exists");
                    return View("Index", await _roleManager.Roles.ToListAsync());
                }
                await _roleManager.CreateAsync(new IdentityRole { Name = model.Name.Trim() });
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Index));
            }
        }



        [Authorize(Permissions.Roles.Update)]
        // GET: RolesController/ManagePermissions/5
        public async Task<IActionResult> ManagePermissions(string roleId)
        {

            var role = await _roleManager.FindByIdAsync(roleId);
            if (role == null) return NotFound();

            var permissions =  _roleManager.GetClaimsAsync(role).Result.Select(c=>c.Value).ToList();


            var viewModel = new CheckBoxGroupViewModel
            {
                GroupId = role.Id,
                GroupName = role.Name,
                CheckboxList = Permissions.GenerateAllPermissions().Select(per => new CheckBoxViewModel
                {
                    CheckBoxValue = per.ToString(),
                    IsSelected = permissions.Contains(per.ToString())
                }).ToList() 
            };

            return View(viewModel);
        }
        // POST: RolesController/UpdatePermissions
        [Authorize(Permissions.Roles.Update)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdatePermissions(CheckBoxGroupViewModel model)
        {
            var role = await _roleManager.FindByIdAsync(model.GroupId);
            if (role == null) return NotFound();
            foreach (var permission in await _roleManager.GetClaimsAsync(role))
            {
                await _roleManager.RemoveClaimAsync(role, permission);
            }


            foreach (var claim in model.CheckboxList.Where(x => x.IsSelected).ToList())
            {
                await _roleManager.AddClaimAsync(role, new System.Security.Claims.Claim(Permissions.PermissionName, claim.CheckBoxValue));
            }

            return RedirectToAction(nameof(Index));


        }

        // GET: RolesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RolesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RolesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RolesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

PermissionsBasedProject/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PermissionsBasedProject.Constants;
using PermissionsBasedProject.Models;

namespace PermissionsBasedProject.Controllers
{
    [Authorize(Permissions.Users.View)]

    public class UsersController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;    
        private readonly SignInManager<IdentityUser> _signInManager;    

        public UsersController(UserManager<IdentityUser> userManager , RoleManager<IdentityRole> roleManager, SignInManager<IdentityUser>signInManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _signInManager = signInManager;
        }


        // GET: UsersController
        [Authorize(Permissions.Users.View)]
        public async Task<IActionResult> Index()
        {
            try
            {
                var users = await _userManager.Users.Select(x => new UserViewModel { Id = x.Id, Email = x.Email, UserName = x.UserName, Roles = _userManager.GetRolesAsync(x).Result }).ToListAsync();
                return View(users);
            }
            catch (Exception ex)
            {
                return NotFound();
            }

            
        }

        // GET: UsersController/ManageRoles/5
        [Authorize(Permissions.Users.Update)]
        public async Task<IActionResult> ManageRoles(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null) return NotFound();

            var roles = await _roleManager.Roles.ToListAsync();

            var viewModel = new CheckBoxGroupViewModel
            {
                GroupId = user.Id, 
                GroupName = user.UserName,
                CheckboxList = roles.Select(role => new CheckBoxViewModel
                {
                    CheckBoxValue = role.Name,
                    IsSelected = _userManager.IsInRoleAsync(user, role.Name).Result
                }).ToList() 
            };

            return View(viewModel);
        }

        // POST: UsersController/UpdateRoles
        [Authorize(Permissions.Users.Update)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateRoles(CheckBoxGroupViewModel model)
        {
            var user = await _userManager.FindByIdAsync(model.GroupId);
            if(user == null) return NotFound();
            var userRoles = await _userManager.GetRolesAsync(user);
            await _userManager.RemoveFromRolesAsync(user, userRoles);
            await _userManager.AddToRolesAsync(user, model.CheckboxList.Where(r=>r.IsSelected).Select(r=>r.CheckBoxValue));

            return RedirectToAction(nameof(Index));


        }


        // GET: UsersController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UsersController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UsersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UsersController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UsersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UsersController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: UsersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

PermissionsBasedProject/Views/Shared/_Layout.cshtml
@inject IAuthorizationService AuthorizationService
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PermissionsBasedProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PermissionsBasedProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PermissionsBasedProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if(AuthorizationService.AuthorizeAsync(User,Permissions.Users.View).Result.Succeeded)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                        }
                        @if(AuthorizationService.AuthorizeAsync(User,Permissions.Roles.View).Result.Succeeded)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                            </li>
                        }

                         @if(AuthorizationService.AuthorizeAsync(User,Permissions.Products.View).Result.Succeeded)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PermissionsBasedProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>